In [10]:
# NumPyをインポート
import numpy as np

 # 多次元配列の作成
multi_array = np.array([[0, 1], [2, 3], [4, 5]])
multi_array = np.array([[0, 1, 2, 3], [4, 5, 6, 7]])
multi_array

# 行列の積の計算
A = np.array([[0, 1], [2, 3], [4, 5]])
B = np.array([[0, 1, 2, 3], [4, 5, 6, 7]])
answer = np.dot(A, B)
print(answer)

# 行列の最大値を求める
multi_array.max()


[[ 4  5  6  7]
 [12 17 22 27]
 [20 29 38 47]]


7